const data = {
  //pricewithdiscount - цена без скидки(without)
  products: [
    {
      id: "1",
      name: "Apple BYZ S852I",
      price: 2927,
      pricewithdiscount: 3527,
      rate: 4.7,
      image: "img/Image-2.png",
      category: "headphones",
    },
    {
      id: "2",
      name: "Apple EarPods",
      price: 2327,
      pricewithdiscount: null,
      rate: 4.5,
      image: "img/Image-1.png",
      category: "headphones",
    },
    {
      id: "3",
      name: "Apple EarPods",
      price: 2327,
      pricewithdiscount: null,
      rate: 4.5,
      image: "img/Image.png",
      category: "headphones",
    },
    {
      id: "4",
      name: "Apple EarPods",
      price: 2327,
      pricewithdiscount: null,
      rate: 4.5,
      image: "img/Image-1.png",
      category: "headphones",
    },
    {
      id: "5",
      name: "Apple EarPods",
      price: 2327,
      pricewithdiscount: null,
      rate: 4.5,
      image: "img/Image-2.png",
      category: "headphones",
    },
    {
      id: "6",
      name: "Apple EarPods",
      price: 2327,
      pricewithdiscount: null,
      rate: 4.5,
      image: "img/Image.png",
      category: "headphones",
    },
    {
      id: "7",
      name: "Apple EarPods",
      price: 9527,
      pricewithdiscount: null,
      rate: 4.7,
      image: "img/Image-5.png",
      category: "wheadphones",
    },
    {
      id: "8",
      name: "GERLAX GH-04",
      price: 6527,
      pricewithdiscount: null,
      rate: 4.7,
      image: "img/Image-4.png",
      category: "wheadphones",
    },
    {
      id: "9",
      name: "BOROFONE BO4",
      price: 7527,
      pricewithdiscount: null,
      rate: 4.7,
      image: "img/Image-3.png",
      category: "wheadphones",
    },
    {
      id: "10",
      name: "BOROFONE ВЫФВЫФВФЫВЫФBO4",
      price: 722527,
      pricewithdiscount: null,
      rate: 4.7,
      image: "img/Image-2.png",
      category: "wheadphones",
    },
    {
      id: "11",
      name: "BOROFONЫААВЫ BO4",
      price: 75127,
      pricewithdiscount: null,
      rate: 4.7,
      image: "img/Image-3.png",
      category: "wheadphones",
    },
  ],
};
export default data;
